# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/yaml-feedstock/recipe, last modified Sat Aug  7 09:30:44 2021
# ------------------------------------------------

package:
  name: yaml
  version: 0.2.5
source:
  sha256: fa240dbf262be053f3898006d502d514936c818e422afdcf33921c63bed9bf2e
  url: https://github.com/yaml/libyaml/archive/0.2.5.tar.gz
build:
  number: '0'
  run_exports:
    - yaml >=0.2.5,<0.3.0a0
  string: h1a28f6b_0
requirements:
  build:
    - autoconf 2.69 pl5340h1230e6a_1
    - automake 1.16.2 pl5340hca03da5_1
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - libtool 2.4.6 h1230e6a_0
    - llvm-tools 12.0.0 h12f7ac0_4
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - perl 5.34.0 h1230e6a_0
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  run: []
test:
  commands:
    - test -f "${PREFIX}/include/yaml.h"
    - test -f "${PREFIX}/lib/libyaml${SHLIB_EXT}"
about:
  description: 'YAML is a human friendly data serialization standard for all programming

    languages.

    '
  dev_url: https://github.com/yaml
  doc_source_url: https://github.com/yaml/www.yaml.org/tree/master/docs
  doc_url: http://www.yaml.org/spec/1.2/spec.html
  home: http://pyyaml.org/wiki/LibYAML
  license: MIT
  license_file: License
  summary: A C library for parsing and emitting YAML
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - seanyen
