# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jan 12 21:46:18 2023
# ------------------------------------------------

package:
  name: nbformat
  version: 5.7.3
source:
  sha256: 4b021fca24d3a747bf4e626694033d792d594705829e5e35b14ee3369f9f6477
  url: https://pypi.io/packages/source/n/nbformat/nbformat-5.7.3.tar.gz
build:
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/nbformat_1673560067442/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - editables 0.3 pyhd8ed1ab_0
    - hatch-nodejs-version 0.3.1 pyhd8ed1ab_0
    - hatchling 1.12.2 pyhd8ed1ab_0
    - importlib-metadata 6.0.0 pyha770c72_0
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h0b41bf4_1
    - packaging 23.0 pyhd8ed1ab_0
    - pathspec 0.10.3 pyhd8ed1ab_0
    - pip 22.3.1 pyhd8ed1ab_0
    - pluggy 1.0.0 pyhd8ed1ab_5
    - python 3.11.0 ha86cf86_0_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 65.6.3 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.11.0 pyhd8ed1ab_0
  run:
    - importlib-metadata >=3.6
    - jsonschema >=2.6
    - jupyter_core
    - python >=3.7
    - python-fastjsonschema
    - traitlets >=5.1
test:
  commands:
    - pip check
    - pip list | grep -iE nbformat
    - pip list | grep -iE 'nbformat\s*5\.7\.3'
    - python -c "v = __import__('nbformat').__version__; print(v); assert v == '5.7.3'"
    - jupyter trust --version
    - jupyter-trust --help
    - pytest -vv --cov=nbformat --cov-branch --cov-report=term-missing:skip-covered
      --no-cov-on-fail --cov-fail-under=76
  imports:
    - nbformat
  requires:
    - pep440
    - pip
    - pytest
    - pytest-cov
    - testpath
  source_files:
    - tests
about:
  description: 'This package contains the base implementation of the Jupyter Notebook
    format,

    and Python APIs for working with notebooks.'
  dev_url: https://github.com/jupyter/nbformat
  doc_url: https://nbformat.readthedocs.io
  home: https://jupyter.org
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: The Jupyter Notebook format
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bollwyvl
    - jakirkham
    - minrk
    - mpacer
    - ocefpaf
    - pelson
    - takluyver
