# This file created by conda-build 3.22.0
# ------------------------------------------------

package:
  name: libgfortran
  version: 5.0.0
source:
  patches:
    - patches/gcc-11.3.0-arm.diff
  sha256: 98438e6cc7294298b474cf0da7655d9a8c8b796421bb0210531c294a950374ed
  url: https://ftp.gnu.org/gnu/gcc/gcc-11.3.0/gcc-11.3.0.tar.gz
build:
  missing_dso_whitelist:
    - '*'
  number: 28
  string: 11_3_0_hca03da5_28
requirements:
  build: []
  run:
    - libgfortran5
test:
  files:
    - gfortran_test.sh
    - hello.f90
    - maths.f90
    - omp-threadprivate.f90
about:
  dev_url: https://gcc.gnu.org/git/?p=gcc.git;a=tree
  doc_url: https://gcc.gnu.org/onlinedocs/
  home: https://gcc.gnu.org/
  license: GPL-3.0-only WITH GCC-exception-3.1
  license_family: GPL
  license_file: COPYING3
  summary: Fortran compiler and libraries from the GNU Compiler Collection
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: f7a664ef-6e8f-4536-bfe7-a6dfe1a2e306
  recipe-maintainers:
    - beckermr
    - isuruf
    - katietz
  remote_url: git@github.com:AnacondaRecipes/gfortran_impl_osx-64-feedstock.git
  sha: 5a7e46121c15d18fd49f886183d4af394289aff0
