# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/clone-hyq5ikas/recipe, last modified Wed Jan 12 15:19:21 2022
# ------------------------------------------------

package:
  name: readline
  version: 8.1.2
source:
  sha256: 7589a2381a8419e68654a47623ce7dfcb756815c8fee726b98f90bf668af7bc6
  url: https://ftp.gnu.org/gnu/readline/readline-8.1.2.tar.gz
build:
  number: '1'
  run_exports:
    - readline >=8.1.2,<9.0a0
  string: h1a28f6b_1
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libiconv 1.16 h1230e6a_0
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - make 4.3 h620ffc9_1
    - pkg-config 0.29.2 h1a28f6b_0
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 h5a0b063_4
  host:
    - ncurses 6.3 h1a28f6b_2
  run:
    - ncurses >=6.3,<7.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libreadline.a
    - test -f ${PREFIX}/lib/libreadline${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libhistory.a
    - test -f ${PREFIX}/lib/libhistory${SHLIB_EXT}
    - python -c "import readline"
  requires:
    - python 3.*
about:
  description: 'The GNU Readline library provides a set of functions for use by applications

    that allow users to edit command lines as they are typed in.

    The Readline library includes additional functions to maintain a list of previously-entered
    command lines,

    to recall and perhaps reedit those lines, and perform csh-like history expansion
    on previous commands.

    '
  dev_url: http://git.savannah.gnu.org/cgit/readline.git/
  doc_url: https://tiswww.case.edu/php/chet/readline/rltop.html
  home: https://tiswww.case.edu/php/chet/readline/rltop.html
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: library for editing command lines as they are typed in
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - asmeurer
    - croth1
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - msarahan
    - ocefpaf
    - pelson
