# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Jul  5 12:40:52 2021
# ------------------------------------------------

package:
  name: tornado
  version: '6.1'
source:
  sha256: 33c6e81d7bd55b468d2e793517c909b139960b6c790a60b7991b9b6b76fb9791
  url: https://pypi.io/packages/source/t/tornado/tornado-6.1.tar.gz
build:
  number: '1'
  script: /Users/runner/miniforge3/conda-bld/tornado_1625488956802/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv
  string: py39h5161555_1
requirements:
  build:
    - ca-certificates 2021.5.30 h033912b_0
    - cctools_osx-64 949.0.1 h6407bdd_22
    - cctools_osx-arm64 949.0.1 h55de48a_22
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h40be2b1_2
    - clangxx 11.1.0 default_he082bbe_1
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - cross-python_osx-arm64 3.9 13_cpython
    - crossenv 1.0 pyhd8ed1ab_1
    - gettext 0.19.8.1 h7937167_1005
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h7660a38_2
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcxx 11.1.0 habf9029_0
    - libffi 3.3 h046ec9c_2
    - libiconv 1.16 haf1e3a3_0
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.0 hd011deb_1
    - llvm-tools 11.1.0 hd011deb_2
    - lz4-c 1.9.3 h046ec9c_0
    - ncurses 6.2 h2e338ed_4
    - openssl 1.1.1k h0d85af4_0
    - popt 1.16 h7b079dc_2002
    - python 3.9.5 hd187cdc_0_cpython
    - readline 8.1 h05e3726_0
    - rsync 3.2.3 h0d3f7e0_2
    - sed 4.7 h3efe00b_1000
    - sqlite 3.36.0 h23a322b_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.10 h0419947_1
    - tzdata 2021a he74cb21_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h7795811_1010
    - zstd 1.5.0 h582d3a0_0
  host:
    - ca-certificates 2021.5.30 h4653dfc_0
    - certifi 2021.5.30 py39h2804cbe_0
    - ncurses 6.2 h9aa5885_4
    - openssl 1.1.1k h27ca646_0
    - pip 21.1.3 pyhd8ed1ab_0
    - python 3.9.5 h54d631c_0_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 hedafd6a_0
    - setuptools 49.6.0 py39h2804cbe_3
    - sqlite 3.36.0 h72a2b83_0
    - tk 8.6.10 hf7e6567_1
    - tzdata 2021a he74cb21_0
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 h31e879b_1009
  run:
    - python >=3.9,<3.10.0a0
    - python >=3.9,<3.10.0a0
    - python_abi 3.9.* *_cp39
test:
  commands:
    - pip check
  imports:
    - tornado
    - tornado.gen
    - tornado.netutil
    - tornado.platform
    - tornado.test
  requires:
    - pip
about:
  description: 'Tornado is a Python web framework and asynchronous networking library.

    By using non-blocking network I/O, Tornado can scale to tens of thousands

    of open connections, making it ideal for long polling, WebSockets, and

    other applications that require a long-lived connection to each user.

    '
  dev_url: https://github.com/tornadoweb/tornado
  doc_source_url: https://github.com/tornadoweb/tornado/blob/stable/docs/index.rst
  doc_url: http://www.tornadoweb.org/en/stable/
  home: http://www.tornadoweb.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  license_url: http://www.apache.org/licenses/LICENSE-2.0
  summary: A Python web framework and asynchronous networking library, originally
    developed at FriendFeed.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
