# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Nov 11 22:56:18 2020
# ------------------------------------------------

package:
    name: libsodium
    version: 1.0.18
source:
    sha256: 6f504490b342a4f8a4c4a02fc9b866cbef8622d5df4e5452b46be121e46636c1
    url: https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
build:
    number: '1'
    run_exports:
        - libsodium >=1.0.18,<1.0.19.0a0
    string: h27ca646_1
requirements:
    build:
        - cctools_osx-arm64 949.0.1 h1c9b417_16
        - clang 11.0.0 1
        - clang-11 11.0.0 default_h000dee7_1
        - clang_osx-arm64 11.0.0 h40be2b1_3
        - clangxx 11.0.0 default_hf57f61e_1
        - compiler-rt 11.0.0 h01488ec_2
        - compiler-rt_osx-64 11.0.0 hd3c4e95_2
        - ld64_osx-64 530 h66d9e41_16
        - ld64_osx-arm64 530 h8c8ad8c_16
        - ldid 2.1.2 h7660a38_2
        - libclang-cpp11 11.0.0 default_h000dee7_1
        - libcxx 11.0.0 h439d374_0
        - libllvm11 11.0.0 hf85e3d2_0
        - libtool 2.4.6 h2e338ed_1006
        - llvm-tools 11.0.0 hf85e3d2_0
        - make 4.3 h22f3db7_1
        - tapi 1100.0.11 h9ce4665_0
        - zlib 1.2.11 h7795811_1010
    host: []
    run: []
test:
    commands:
        - test -f ${PREFIX}/include/sodium.h
        - test -f ${PREFIX}/lib/libsodium.a
        - test -f ${PREFIX}/lib/libsodium.dylib
about:
    description: 'Sodium is a new, easy-to-use software library for encryption, decryption,

        signatures, password hashing and more. It is a portable, cross-compilable,

        installable, packageable fork of NaCl, with a compatible API, and an

        extended API to improve usability even further. Its goal is to provide all

        of the core operations needed to build higher-level cryptographic tools.

        '
    dev_url: https://github.com/jedisct1/libsodium
    doc_url: https://download.libsodium.org/doc
    home: http://libsodium.org
    license: ISC
    license_file: LICENSE
    summary: A modern and easy-to-use crypto library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
