# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_5dbc68ad-082a-4266-8a8c-155fd5a71461ci4myp3p/clone/recipe, last modified Fri Apr 22 09:28:04 2022
# ------------------------------------------------

package:
  name: zlib
  version: 1.2.12
source:
  patches:
    - cmake-pkg-config.patch
  sha256: 91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9
  url: http://zlib.net/zlib-1.2.12.tar.gz
build:
  number: '2'
  run_exports:
    - zlib >=1.2.12,<1.3.0a0
  string: h5a0b063_2
requirements:
  build:
    - clang_bootstrap_osx-arm64 12.0.0 ha993bc6_3
    - cmake-no-system 3.16.5 hc377ac9_2
    - libcxx 12.0.0 hf6beb65_1
    - make 4.3 h620ffc9_1
    - patch 2.7.6 h1a28f6b_1001
  host:
    - ripgrep 12.1.1 h834c97f_0
  run: []
test:
  commands:
    - test -f ${PREFIX}/include/zlib.h
    - test -f ${PREFIX}/lib/libz.a
    - test -f ${PREFIX}/lib/libz.dylib
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib
  doc_url: https://zlib.net/manual.html
  home: https://zlib.net/
  license: Zlib
  license_family: Other
  license_file: zlib.h
  summary: Massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 5dbc68ad-082a-4266-8a8c-155fd5a71461
  recipe-maintainers:
    - groutr
    - mingwandroid
    - msarahan
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/zlib-feedstock.git
  sha: a0ce994cd24967a361c0c40da7cea2c28025e2a6
