# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Oct 11 22:13:28 2021
# ------------------------------------------------

package:
  name: argon2-cffi
  version: 21.1.0
source:
  fn: argon2-cffi-21.1.0.tar.gz
  sha256: f710b61103d1a1f692ca3ecbd1373e28aa5e545ac625ba067ff2feca1b2bb870
  url: https://pypi.io/packages/source/a/argon2-cffi/argon2-cffi-21.1.0.tar.gz
build:
  number: '0'
  script:
    - ln -sf $RANLIB $BUILD_PREFIX/bin/ranlib
    - /Users/runner/miniforge3/conda-bld/argon2-cffi_1633990794010/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
      -m pip install . -vv
  string: py39h5161555_0
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 949.0.1 h6407bdd_22
    - cctools_osx-arm64 949.0.1 h55de48a_22
    - cffi 1.14.6 py39he338e87_1
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h40be2b1_3
    - clangxx 11.1.0 default_he082bbe_1
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - cross-python_osx-arm64 3.9 13_cpython
    - crossenv 1.0 pyhd8ed1ab_2
    - gettext 0.19.8.1 hd1a6beb_1008
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h6a69015_3
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcxx 12.0.1 habf9029_0
    - libffi 3.4.2 he49afe7_4
    - libiconv 1.16 haf1e3a3_0
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.1 hd011deb_2
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 11.1.0 hd011deb_2
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.2 h2e338ed_4
    - openssl 3.0.0 h0d85af4_1
    - popt 1.16 h7b079dc_2002
    - pycparser 2.20 pyh9f0ad1d_2
    - python 3.9.7 h38b4d05_3_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h05e3726_0
    - rsync 3.2.3 h652f650_3
    - sed 4.7 h3efe00b_1000
    - sqlite 3.36.0 h23a322b_2
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.11 h5dbffcc_1
    - tzdata 2021c he74cb21_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h9173be1_1013
    - zstd 1.5.0 h582d3a0_0
  host:
    - ca-certificates 2021.10.8 h4653dfc_0
    - cffi 1.14.6 py39h52b1de0_1
    - libcxx 12.0.1 h168391b_0
    - libffi 3.4.2 hbdafb3b_4
    - libzlib 1.2.11 hee7b306_1013
    - ncurses 6.2 h9aa5885_4
    - openssl 3.0.0 h3422bc3_1
    - pip 21.2.4 pyhd8ed1ab_0
    - pycparser 2.20 pyh9f0ad1d_2
    - python 3.9.7 hc0da0df_3_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 hedafd6a_0
    - setuptools 58.2.0 py39h2804cbe_0
    - six 1.16.0 pyh6c4a22f_0
    - sqlite 3.36.0 h72a2b83_2
    - tk 8.6.11 he1e0b03_1
    - tzdata 2021c he74cb21_0
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 hee7b306_1013
  run:
    - cffi >=1.0.0
    - python >=3.9,<3.10.0a0
    - python >=3.9,<3.10.0a0
    - python_abi 3.9.* *_cp39
    - six
  run_constrained:
    - argon2_cffi ==999
test:
  imports:
    - argon2
about:
  description: 'Argon2 won the Password Hashing Competition and argon2_cffi is the
    simplest

    way to use it in Python and PyPy

    '
  dev_url: https://github.com/hynek/argon2_cffi/
  doc_url: https://argon2-cffi.readthedocs.io/en/stable/
  home: https://argon2-cffi.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The secure Argon2 password hashing algorithm.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - stuertz
