# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Feb  5 03:29:04 2023
# ------------------------------------------------

package:
  name: websocket-client
  version: 1.5.1
source:
  sha256: 3f09e6d8230892547132177f575a4e3e73cfdf06526e20cc02aa1c3b47184d40
  url: https://pypi.io/packages/source/w/websocket-client/websocket-client-1.5.1.tar.gz
build:
  entry_points:
    - wsdump=websocket._wsdump:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/websocket-client_1675567828044/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h0b41bf4_2
    - pip 23.0 pyhd8ed1ab_0
    - python 3.11.0 he550d4f_1_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 67.1.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  commands:
    - pip check
    - wsdump --help
  imports:
    - websocket
    - websocket.tests
  requires:
    - pip
about:
  dev_url: https://github.com/websocket-client/websocket-client/
  doc_url: https://websocket-client.readthedocs.io/en/latest/
  home: https://github.com/websocket-client/websocket-client.git
  license: Apache-2.0
  license_file: LICENSE
  summary: WebSocket client for Python with low level API options
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - BastianZim
    - scopatz
    - wshanks
