# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_clone-30qtu51f/recipe, last modified Wed Apr  6 02:33:40 2022
# ------------------------------------------------

package:
  name: setuptools
  version: 61.2.0
source:
  patches:
    - patches/0002-disable-downloads-inside-conda-build.patch
    - patches/0006-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
    - patches/0012-Disable-new-dtags-in-unixccompiler.py.patch
    - patches/0019-Use-ranlib-from-env-if-env-variable-is-set.patch
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
    - patches/0035-pypy-distutils-scheme.patch
  sha256: c3d4e2ab578fbf83775755cd76dae73627915a22832cf4ea5de895978767833b
  url: https://pypi.io/packages/source/s/setuptools/setuptools-61.2.0.tar.gz
build:
  number: '0'
  string: py39hca03da5_0
requirements:
  build:
    - patch 2.7.6 h1a28f6b_1001
  host:
    - ca-certificates 2022.3.29 hca03da5_0
    - certifi 2021.10.8 py39hca03da5_2
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.4.2 hc377ac9_2
    - ncurses 6.3 h1a28f6b_2
    - openssl 1.1.1n h1a28f6b_0
    - python 3.9.12 hbdb9e5c_0
    - readline 8.1.2 h1a28f6b_1
    - sqlite 3.38.2 h1058600_0
    - tk 8.6.11 hb8d0fd4_0
    - tzdata 2022a hda174b7_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 h5a0b063_4
  run:
    - certifi >=2016.9.26
    - python >=3.9,<3.10.0a0
test:
  imports:
    - pkg_resources
    - setuptools
about:
  description: 'Setuptools is a fully-featured, actively-maintained, and stable library

    designed to facilitate packaging Python projects.

    '
  dev_url: https://github.com/pypa/setuptools
  doc_source_url: https://github.com/pypa/setuptools/tree/master/docs
  doc_url: https://setuptools.pypa.io/en/latest/
  home: https://github.com/pypa/setuptools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download, build, install, upgrade, and uninstall Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: cfb00be7-3fb0-4a46-8547-213b0e2aa591
  recipe-maintainers:
    - isuruf
    - jakirkham
    - msarahan
    - nicoddemus
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/setuptools-feedstock.git
  sha: 8bf94ce0f61569fa46790641b636d9884658a203
