# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Feb  7 02:07:30 2023
# ------------------------------------------------

package:
  name: platformdirs
  version: 3.0.0
source:
  sha256: 8a1228abb1ef82d788f74139988b137e78692984ec7b08eaa6c65f1723af28f9
  url: https://pypi.io/packages/source/p/platformdirs/platformdirs-3.0.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/platformdirs_1675735718929/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - editables 0.3 pyhd8ed1ab_0
    - hatch-vcs 0.3.0 pyhd8ed1ab_0
    - hatchling 1.12.2 pyhd8ed1ab_0
    - importlib-metadata 6.0.0 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h0b41bf4_2
    - packaging 23.0 pyhd8ed1ab_0
    - pathspec 0.11.0 pyhd8ed1ab_0
    - pip 23.0 pyhd8ed1ab_0
    - pluggy 1.0.0 pyhd8ed1ab_5
    - python 3.11.0 he550d4f_1_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 67.1.0 pyhd8ed1ab_0
    - setuptools-scm 7.1.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.4.0 hd8ed1ab_0
    - typing_extensions 4.4.0 pyha770c72_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.12.1 pyhd8ed1ab_0
  run:
    - python >=3.7
    - typing-extensions >=4.4
test:
  commands:
    - pip check
  imports:
    - platformdirs
  requires:
    - pip
about:
  dev_url: https://github.com/platformdirs/platformdirs
  home: https://github.com/platformdirs/platformdirs
  license: MIT
  license_file: LICENSE
  summary: A small Python module for determining appropriate platform-specific dirs,
    e.g. a "user data dir".
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - adament
    - bollwyvl
    - gaborbernat
