# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: python
  version: 3.9.12
source:
  - patches:
      - patches/0001-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
      - patches/0002-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0003-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0004-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0005-Support-cross-compiling-byte-code.patch
      - patches/0006-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - patches/0007-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
      - patches/0008-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0009-Win32-Do-not-download-externals.patch
      - patches/0010-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
      - patches/0011-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0012-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0013-Fix-cross-compilation-on-Debian-based-distros.patch
      - patches/0014-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0015-Unvendor-openssl.patch
      - patches/0016-Unvendor-sqlite3.patch
      - patches/0017-venv-Revert-a-change-from-https-github.com-python-cp.patch
      - patches/0018-Win-Add-back-the-DLLSuffix-used-to-find-the-openssl-.patch
      - patches/0019-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0020-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
      - patches/0022-Doing-d1trimfile.patch
      - patches/0023-egg-debugging-with-Windows-debug-builds.patch
      - patches/0024-Add-CONDA_DLL_SEARCH_MODIFICATION_KEEP_GIL-to-aid-de.patch
      - patches/0025-cross-compile-darwin.patch
      - patches/0032-Fix-TZPATH-on-windows.patch
      - patches/0033-gh24324.patch
      - patches/0034-have-pyunicode-decodeunicodeescape.patch
      - patches/9999-Add-Anaconda-Distribution-version-logic.patch
    sha256: 2cd94b20670e4159c6d9ab57f91dbf255b97d8c1a1451d1c35f4ec1968adf971
    url: https://www.python.org/ftp/python/3.9.12/Python-3.9.12.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  ignore_run_exports:
    - bzip2
    - clangxx_osx-64
  missing_dso_whitelist: null
  no_link: null
  number: 0
  script_env:
    - CONDA_FORGE=no
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
  string: hbdb9e5c_0
requirements:
  build:
    - ccache 3.7.9 h6b60437_0
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - gettext 0.21.0 h826f4ad_0
    - icu 68.1 hc377ac9_0
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libiconv 1.16 h1a28f6b_1
    - libllvm12 12.0.0 h12f7ac0_4
    - libtool 2.4.6 hc377ac9_1008
    - libxml2 2.9.12 h8c5e841_0
    - llvm-openmp 12.0.0 haf9daa7_1
    - llvm-tools 12.0.0 h12f7ac0_4
    - make 4.3 h620ffc9_1
    - pkg-config 0.29.2 h1a28f6b_0
    - ripgrep 12.1.1 h834c97f_0
    - sed 4.8 h1a28f6b_0
    - tapi 1100.0.11 ha21211d_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 h5a0b063_4
  host:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2022.3.29 hca03da5_0
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.3 hc377ac9_2
    - ncurses 6.3 h1a28f6b_2
    - openssl 1.1.1n h1a28f6b_0
    - readline 8.1.2 h1a28f6b_1
    - sqlite 3.38.2 h1058600_0
    - tk 8.6.11 hb8d0fd4_0
    - unzip 6.0 h1a28f6b_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 h5a0b063_4
  run:
    - libcxx >=12.0.0
    - libffi >=3.3,<4.0a0
    - ncurses >=6.3,<7.0a0
    - openssl >=1.1.1n,<1.1.2a
    - readline >=8.1.2,<9.0a0
    - sqlite >=3.38.2,<4.0a0
    - tk >=8.6.11,<8.7.0a0
    - tzdata
    - xz >=5.2.5,<6.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python run_test.py
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd embedding-interpreter
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - bash run_cmake_test.sh 3.9.12
    - popd
    - pushd processpoolexecutor-max_workers-61
    - python ppe.py
    - popd
    - popd
    - test ! -f default.profraw
  downstreams:
    - cython
    - setuptools
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils/*
    - tests/embedding-interpreter/*
    - tests/processpoolexecutor-max_workers-61/*
  requires:
    - clang_osx-arm64 12.*
    - clangxx_osx-arm64 12.*
    - cmake
    - make
    - ninja
    - ripgrep
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://docs.python.org/devguide/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  flow_run_id: 3f67e40d-685b-447a-b9f7-263cbe31a8b6
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/python-feedstock.git
  sha: f06591dd2ec5edb18c3fc0f785898b2838a39577
