# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Nov 28 10:39:52 2022
# ------------------------------------------------

package:
  name: stack_data
  version: 0.6.2
source:
  sha256: 32d2dd0376772d01b6cb9fc996f3c8b57a357089dec328ed4b6553d037eaf815
  url: https://pypi.io/packages/source/s/stack_data/stack_data-0.6.2.tar.gz
build:
  noarch: python
  number: '0'
  script: '/home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . --no-deps --ignore-installed -vvv '
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.9.24 ha878542_0
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h166bdaf_0
    - packaging 21.3 pyhd8ed1ab_0
    - pip 22.3.1 pyhd8ed1ab_0
    - pyparsing 3.0.9 pyhd8ed1ab_0
    - python 3.11.0 ha86cf86_0_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 65.5.1 pyhd8ed1ab_0
    - setuptools-scm 7.0.5 pyhd8ed1ab_1
    - setuptools_scm 7.0.5 hd8ed1ab_1
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.4.0 hd8ed1ab_0
    - typing_extensions 4.4.0 pyha770c72_0
    - tzdata 2022f h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - asttokens
    - executing
    - pure_eval
    - python >=3.5
test:
  commands:
    - pip check
  imports:
    - stack_data
  requires:
    - pip
about:
  dev_url: http://github.com/alexmojaki/stack_data
  doc_url: http://github.com/alexmojaki/stack_data
  home: http://github.com/alexmojaki/stack_data
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Extract data from python stack frames and tracebacks for informative displays
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - alexmojaki
