# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jan  2 17:52:01 2023
# ------------------------------------------------

package:
  name: pygments
  version: 2.14.0
source:
  sha256: b3ed06a9e8ac9a9aae5a6f5dbe78a8a58655d17b43b93c078f094ddc476ae297
  url: https://pypi.io/packages/source/p/pygments/Pygments-2.14.0.tar.gz
build:
  entry_points:
    - pygmentize = pygments.cmdline:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pygments_1672682006896/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h0b41bf4_1
    - pip 22.3.1 pyhd8ed1ab_0
    - python 3.11.0 ha86cf86_0_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 65.6.3 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.6
    - setuptools
test:
  commands:
    - pip check
    - pygmentize -h
  imports:
    - pygments
    - pygments.filters
    - pygments.formatters
    - pygments.lexers
    - pygments.plugin
    - pygments.styles
  requires:
    - pip
about:
  home: http://pygments.org/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Pygments is a generic syntax highlighter suitable for use in code hosting,
    forums, wikis or other applications that need to prettify source code.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
    - scopatz
