# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jun  8 23:25:57 2022
# ------------------------------------------------

package:
  name: jupyter_client
  version: 7.3.4
source:
  sha256: aa9a6c32054b290374f95f73bb0cae91455c58dfb84f65c8591912b8f65e6d56
  url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-7.3.4.tar.gz
build:
  entry_points:
    - jupyter-kernel = jupyter_client.kernelapp:main
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/jupyter_client_1654730843242/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.5.18.1 ha878542_0
    - editables 0.3 pyhd8ed1ab_0
    - hatchling 1.3.1 pyhd8ed1ab_0
    - importlib-metadata 4.11.4 py310hff52083_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.1.0 h8d9b700_16
    - libgomp 12.1.0 h8d9b700_16
    - libnsl 2.0.0 h7f98852_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.12 h166bdaf_0
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.3 h166bdaf_0
    - packaging 21.3 pyhd8ed1ab_0
    - pathspec 0.9.0 pyhd8ed1ab_0
    - pip 22.1.2 pyhd8ed1ab_0
    - pluggy 1.0.0 py310hff52083_3
    - pyparsing 3.0.9 pyhd8ed1ab_0
    - python 3.10.4 h2660328_0_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1 h46c0cb4_0
    - setuptools 62.3.3 py310hff52083_0
    - sqlite 3.38.5 h4ff8645_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2022a h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h516909a_1
    - zipp 3.8.0 pyhd8ed1ab_0
    - zlib 1.2.12 h166bdaf_0
  run:
    - entrypoints
    - jupyter_core >=4.9.2
    - nest-asyncio >=1.5.4
    - python >=3.7
    - python-dateutil >=2.8.2
    - pyzmq >=23.0
    - tornado >=6.0
    - traitlets
test:
  commands:
    - pip check
    - jupyter kernelspec list
    - jupyter run -h
    - pytest --pyargs jupyter_client --cov jupyter_client --cov-report term-missing:skip-covered
      --no-cov-on-fail -k "not test_signal_kernel_subprocesses"
  imports:
    - jupyter_client
  requires:
    - async_generator
    - ipykernel
    - ipython
    - mock
    - pip
    - pytest
    - pytest-asyncio
    - pytest-cov
    - pytest-timeout
about:
  dev_url: https://github.com/jupyter/jupyter_client
  doc_source_url: https://github.com/jupyter/jupyter_client/tree/master/docs
  doc_url: https://jupyter-client.readthedocs.io/en/stable/
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - blink1073
    - bollwyvl
    - carreau
    - davidbrochart
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
