# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/tmpugxnxm4j/recipe, last modified Mon Nov 22 08:45:42 2021
# ------------------------------------------------

package:
  name: grpcio
  version: 1.42.0
source:
  patches:
    - 0001-Monkey-patch-distutils.ccompiler.spawn-to-elide-std-.patch
    - 0001-fix-win-commands.patch
    - 0002-windows-ssl-lib-names.patch
  sha256: 4a8f2c7490fe3696e0cdd566e2f099fb91b51bc75446125175c55581c2f7bc11
  url: https://pypi.io/packages/source/g/grpcio/grpcio-1.42.0.tar.gz
build:
  missing_dso_whitelist: null
  number: '0'
  string: py39h95c9599_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - patch 2.7.6 h1a28f6b_1001
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  host:
    - c-ares 1.17.1 h1a28f6b_0
    - ca-certificates 2021.10.26 hca03da5_2
    - certifi 2021.5.30 py39hca03da5_1
    - coverage 5.5 py39h1a28f6b_2
    - cython 0.29.24 py39hc377ac9_0
    - expat 2.4.1 hc377ac9_2
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.4.2 hc377ac9_2
    - libiconv 1.16 h1230e6a_0
    - ncurses 6.3 h1a28f6b_2
    - openssl 1.1.1j h1230e6a_0
    - pip 21.2.4 py39hca03da5_0
    - python 3.9.7 hc70090a_1
    - readline 8.1 h1a28f6b_0
    - setuptools 52.0.0 py39hca03da5_1
    - six 1.16.0 pyhd3eb1b0_0
    - sqlite 3.36.0 h1058600_0
    - tk 8.6.11 hb8d0fd4_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 hca03da5_3
  run:
    - c-ares >=1.17.1,<2.0a0
    - libcxx >=12.0.0
    - openssl >=1.1.1j,<1.1.2a
    - python >=3.9,<3.10.0a0
    - six >=1.5.2
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - python -m pip check
  imports:
    - grpc
    - grpc._cython
    - grpc._cython._cygrpc
    - grpc.beta
    - grpc.framework
    - grpc.framework.common
    - grpc.framework.foundation
    - grpc.framework.interfaces
    - grpc.framework.interfaces.base
    - grpc.framework.interfaces.face
  requires:
    - pip
about:
  dev_url: https://pypi.org/project/grpcio/
  home: https://grpc.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: HTTP/2-based RPC framework
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bollwyvl
    - jcrist
    - ocefpaf
    - tswast
