# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Oct 18 13:36:14 2022
# ------------------------------------------------

package:
  name: tinycss2
  version: 1.2.1
source:
  sha256: 8cff3a8f066c2ec677c06dbc7b45619804a6938478d9d73c284b29d14ecb0627
  url: https://pypi.io/packages/source/t/tinycss2/tinycss2-1.2.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/tinycss2_1666100256010/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - attrs 22.1.0 pyh71513ae_1
    - brotlipy 0.7.0 py310h5764c6d_1004
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.9.24 ha878542_0
    - certifi 2022.9.24 pyhd8ed1ab_0
    - cffi 1.15.1 py310h255011f_0
    - charset-normalizer 2.1.1 pyhd8ed1ab_0
    - cryptography 38.0.2 py310h597c629_0
    - docutils 0.19 py310hff52083_0
    - flit 3.7.1 pyhd8ed1ab_0
    - flit-core 3.7.1 pyhd8ed1ab_0
    - idna 3.4 pyhd8ed1ab_0
    - iniconfig 1.1.1 pyh9f0ad1d_0
    - ld_impl_linux-64 2.39 hc81fddc_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_18
    - libgomp 12.2.0 h65d4601_18
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.39.4 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 1.1.1q h166bdaf_0
    - packaging 21.3 pyhd8ed1ab_0
    - pip 22.3 pyhd8ed1ab_0
    - pluggy 1.0.0 py310hff52083_3
    - py 1.11.0 pyh6c4a22f_0
    - pycparser 2.21 pyhd8ed1ab_0
    - pyopenssl 22.1.0 pyhd8ed1ab_0
    - pyparsing 3.0.9 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - pytest 7.1.3 py310hff52083_0
    - pytest-runner 6.0.0 pyhd8ed1ab_0
    - python 3.10.6 h582c2e5_0_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1.2 h0f457ee_0
    - requests 2.28.1 pyhd8ed1ab_1
    - setuptools 65.5.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tomli-w 1.0.0 pyhd8ed1ab_0
    - tzdata 2022e h191b570_0
    - urllib3 1.26.11 pyhd8ed1ab_0
    - webencodings 0.5.1 py_1
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.5
    - webencodings >=0.4
test:
  imports:
    - tinycss2
about:
  description: 'tinycss2 is a rewrite of tinycss with a simpler API, based on the
    more recent

    CSS Syntax Level 3 Specification.

    '
  dev_url: https://github.com/Kozea/tinycss2
  doc_url: http://tinycss2.readthedocs.io
  home: https://github.com/Kozea/tinycss2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Low-level CSS parser for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - johanneskoester
    - mrandrewandrade
    - thewchan
