CONDA_BUILD_SYSROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
MACOSX_DEPLOYMENT_TARGET: '11.1'
VERBOSE_AT: V=1
VERBOSE_CM: VERBOSE=1
apr: 1.6.3
blas_impl: openblas
boost: '1.73'
boost_cpp: '1.73'
bzip2: '1.0'
c_compiler: clang
c_compiler_version: '12'
cairo: '1.16'
channel_targets: defaults
clang_variant: clang
cpu_optimization_target: nocona
cran_mirror: https://mran.microsoft.com/snapshot/2018-01-01
cxx_compiler: clangxx
cxx_compiler_version: '12'
cyrus_sasl: 2.1.27
dbus: '1'
expat: '2.4'
extend_keys:
- ignore_version
- pin_run_as_build
- extend_keys
- ignore_build_only_deps
fontconfig: '2.13'
fortran_compiler: gfortran
freetype: '2.10'
g2clib: '1.6'
geos: 3.8.0
giflib: '5'
glib: '2'
gmp: '6.2'
gnu: 2.12.2
gst_plugins_base: '1.14'
gstreamer: '1.14'
harfbuzz: '2.8'
hdf4: '4.2'
hdf5: 1.12.0
hdfeos2: '2.20'
hdfeos5: '5.1'
icu: '68'
ignore_build_only_deps:
- python
- numpy
jpeg: '9'
libdap4: '3.19'
libffi: '3.3'
libgd: 2.2.5
libgdal: '3.0'
libgsasl: '1.8'
libkml: '1.3'
libnetcdf: '4.6'
libpng: '1.6'
libprotobuf: 3.17.2
libtiff: '4.2'
libwebp: 1.2.0
libxml2: '2.9'
libxslt: '1.1'
llvm_variant: llvm
lua: '5'
lzo: '2'
macos_machine: arm64-apple-darwin20.0.0
macos_min_version: '11.1'
mkl: '2021'
mpfr: '4'
noarch_python: python
numpy: '1.21'
openblas: 0.3.17
openjpeg: '2.3'
openssl: 1.1.1
perl: '5.34'
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libboost:
    max_pin: x.x.x
pixman: '0.40'
proj: 6.2.1
proj4: 5.2.0
python: '3.8'
python_impl: cpython
python_implementation: cpython
qtwebkit: 'true'
r_base: '3.5'
r_implementation: r-base
r_version: 3.5.0
readline: '8.1'
rust_compiler: rust
rust_compiler_version: 1.46.0
serf: 1.3.9
sqlite: '3'
target_platform: osx-arm64
tk: '8.6'
xz: '5'
zlib: '1.2'
