# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_6e60ba46-e080-4cd2-a6bd-161b8355415cxjsxg3q3/clone/recipe, last modified Mon May  2 15:59:16 2022
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2022.4.26
source:
  fn: cacert.pem
  sha256: 08df40e8f528ed283b0e480ba4bcdbfdd2fdcf695a7ada1668243072d80f8b6f
  url: https://curl.haxx.se/ca/cacert-2022-04-26.pem
build:
  number: '0'
  string: hca03da5_0
requirements:
  build: []
  run: []
test:
  commands:
    - pip check
  requires:
    - curl
    - pip
about:
  dev_url: https://github.com/curl/curl/blob/master/scripts/mk-ca-bundle.pl
  doc_url: https://github.com/curl/curl/blob/master/docs/SSLCERTS.md
  home: https://curl.se/docs/caextract.html
  license: MPL-2.0
  license_family: Other
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 6e60ba46-e080-4cd2-a6bd-161b8355415c
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/ca-certificates-feedstock.git
  sha: 926e3fe5cbf6113bc88efcaea415e6ae16ab5626
