# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jan  2 17:42:24 2023
# ------------------------------------------------

package:
  name: importlib_resources
  version: 5.10.2
source:
  sha256: e4a96c8cc0339647ff9a5e0550d9f276fc5a01ffa276012b58ec108cfd7b8484
  url: https://pypi.io/packages/source/i/importlib_resources/importlib_resources-5.10.2.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/importlib_resources_1672681417544/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h0b41bf4_1
    - packaging 22.0 pyhd8ed1ab_0
    - pip 22.3.1 pyhd8ed1ab_0
    - python 3.11.0 ha86cf86_0_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 65.6.3 pyhd8ed1ab_0
    - setuptools-scm 7.1.0 pyhd8ed1ab_0
    - setuptools_scm 7.1.0 hd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - toml 0.10.2 pyhd8ed1ab_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.4.0 hd8ed1ab_0
    - typing_extensions 4.4.0 pyha770c72_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
    - zipp >=3.1.0
  run_constrained:
    - importlib-resources >=5.10.2,<5.10.3.0a0
test:
  commands:
    - pip check
  imports:
    - importlib_resources
  requires:
    - pip
about:
  home: http://importlib-resources.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE
  summary: Backport of Python 3.7's standard library `importlib.resources`
extra:
  copy_test_source_files: true
  feedstock-name: importlib_resources
  final: true
  recipe-maintainers:
    - ocefpaf
