# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/python.app-feedstock/recipe, last modified Sat Aug  7 09:30:10 2021
# ------------------------------------------------

package:
  name: python.app
  version: '3'
build:
  number: '0'
  string: py39h1a28f6b_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  host:
    - ca-certificates 2021.7.5 hca03da5_1
    - certifi 2021.5.30 py39hca03da5_0
    - expat 2.4.1 hc377ac9_2
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.3 hc4ed4cf_2
    - libiconv 1.16 h1230e6a_0
    - ncurses 6.2 hc4ed4cf_0
    - openssl 1.1.1j h1230e6a_0
    - pip 21.2.3 py39hca03da5_0
    - python 3.9.6 hc70090a_5
    - readline 8.1 h1a28f6b_0
    - setuptools 52.0.0 py39hca03da5_0
    - sqlite 3.36.0 h1058600_0
    - tk 8.6.10 hb8d0fd4_0
    - tzdata 2021a h5d7bf9c_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 hca03da5_3
  run:
    - python >=3.9,<3.10.0a0
test:
  commands:
    - python.app -V
    - pythonw -V
  files:
    - t.py
about:
  home: https://www.python.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Proxy on macOS letting Python libraries hook into the GUI event loop
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ChrisBarker-NOAA
    - cpbotha
    - hoechenberger
