# This file created by conda-build 3.23.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Dec  5 15:20:17 2022
# ------------------------------------------------

package:
  name: terminado
  version: 0.17.1
source:
  sha256: 6ccbbcd3a4f8a25a5ec04991f39a0b8db52dfcd487ea0e578d977e6752380333
  url: https://pypi.io/packages/source/t/terminado/terminado-0.17.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /Users/runner/miniforge3/conda-bld/terminado_1670254106711/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . -vv
  string: pyhd1c38e8_0
requirements:
  host:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.9.24 h033912b_0
    - editables 0.3 pyhd8ed1ab_0
    - hatchling 1.11.1 pyhd8ed1ab_0
    - importlib-metadata 5.1.0 pyha770c72_0
    - libffi 3.4.2 h0d85af4_5
    - libsqlite 3.40.0 ha978bb4_0
    - libzlib 1.2.13 hfd90126_4
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.7 hfd90126_1
    - packaging 21.3 pyhd8ed1ab_0
    - pathspec 0.10.2 pyhd8ed1ab_0
    - pip 22.3.1 pyhd8ed1ab_0
    - pluggy 1.0.0 pyhd8ed1ab_5
    - pyparsing 3.0.9 pyhd8ed1ab_0
    - python 3.11.0 h559f36b_0_cpython
    - python_abi 3.11 3_cp311
    - readline 8.1.2 h3899abd_0
    - setuptools 65.5.1 pyhd8ed1ab_0
    - tk 8.6.12 h5dbffcc_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tornado 6.2 py311h5547dcb_1
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h775f41a_0
    - zipp 3.11.0 pyhd8ed1ab_0
  run:
    - __osx
    - ptyprocess
    - python >=3.7
    - tornado >=6.1.0
test:
  commands:
    - pip check
    - pip list
    - pip list | grep -iE "terminado\s*0\.17\.1"
  imports:
    - terminado
  requires:
    - __osx
    - pip
    - pytest >=6.0
    - pytest-cov
    - pytest-timeout
about:
  description: 'This is a Tornado websocket backend for the Xterm.js Javascript terminal
    emulator library.

    '
  dev_url: https://github.com/jupyter/terminado
  doc_source_url: https://github.com/jupyter/terminado/blob/master/doc/index.rst
  doc_url: http://terminado.readthedocs.org/en/latest/
  home: https://github.com/jupyter/terminado
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Terminals served by tornado websockets
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - blink1073
    - bollwyvl
    - ocefpaf
    - pelson
    - takluyver
