# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: numpy
  version: 1.22.3
source:
  patches:
    - patches/0001-Obtain-and-prefer-custom-gfortran-from-env-variable.patch
  sha256: a906c0b4301a3d62ccf66d058fe779a65c1c34f6719ef2058f96e1856f48bca5
  url: https://github.com/numpy/numpy/releases/download/v1.22.3/numpy-1.22.3.tar.gz
build:
  number: 0
  string: py39h25ab29e_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - clangxx_osx-arm64 12.0.0 h39b79ac_3
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.12 h5a0b063_2
  host:
    - blas 1.0 openblas
    - ca-certificates 2022.4.26 hca03da5_0
    - certifi 2021.10.8 py39hca03da5_2
    - cython 0.29.28 py39hc377ac9_0
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.4.2 hc377ac9_2
    - libgfortran 5.0.0 11_1_0_h6a59814_26
    - libgfortran5 11.1.0 h6a59814_26
    - libopenblas 0.3.17 h9886b1c_1
    - llvm-openmp 12.0.0 haf9daa7_1
    - ncurses 6.3 h1a28f6b_2
    - nomkl 3.0 0
    - openblas-devel 0.3.17 hca03da5_1
    - openssl 1.1.1o h1a28f6b_0
    - packaging 21.3 pyhd3eb1b0_0
    - pyparsing 3.0.4 pyhd3eb1b0_0
    - python 3.9.12 hbdb9e5c_0
    - readline 8.1.2 h1a28f6b_1
    - setuptools 58.0.4 py39hca03da5_1
    - sqlite 3.38.3 h1058600_0
    - tk 8.6.11 hb8d0fd4_1
    - tzdata 2022a hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h1a28f6b_1
    - zlib 1.2.12 h5a0b063_2
  run:
    - blas * openblas
    - libcxx >=12.0.0
    - libopenblas >=0.3.17,<1.0a0
    - numpy-base 1.22.3 py39h974a1f5_0
    - python >=3.9,<3.10.0a0
test:
  commands:
    - f2py -h
    - python -c "import numpy; numpy.show_config()"
    - export OPENBLAS_NUM_THREADS=1
    - pytest -vvv --pyargs numpy -k "not (_not_a_real_test or test_unary_PyUFunc_O_O_method_full[reciprocal]
      or test_new_policy or test_limited_api)" --durations=0
  imports:
    - numpy
    - numpy.core.multiarray
    - numpy.core.numeric
    - numpy.core.umath
    - numpy.linalg.lapack_lite
    - numpy.random.mtrand
  requires:
    - hypothesis
    - pip
    - pytest
    - setuptools <60.0.0
about:
  description: 'NumPy is the fundamental package needed for scientific computing with
    Python.

    '
  dev_source_url: https://github.com/numpy/numpy/tree/master/doc
  dev_url: https://github.com/numpy/numpy
  doc_url: https://docs.scipy.org/doc/numpy/reference/
  home: https://numpy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  lisense_family: BSD
  summary: Array processing for numbers, strings, records, and objects.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ba5c3eaa-be93-4f42-ae24-fa720a3c6627
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
    - rgommers
  remote_url: git@github.com:AnacondaRecipes/numpy-feedstock.git
  sha: 0703252fab2cc38334b41e78094a3b3235f5e204
