# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jan 30 20:28:05 2023
# ------------------------------------------------

package:
  name: traitlets
  version: 5.9.0
source:
  sha256: f6cde21a9c68cf756af02035f72d5a723bf607e862e7be33ece505abf4a3bad9
  url: https://pypi.io/packages/source/t/traitlets/traitlets-5.9.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/traitlets_1675110562325/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - editables 0.3 pyhd8ed1ab_0
    - hatchling 1.12.2 pyhd8ed1ab_0
    - importlib-metadata 6.0.0 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h0b41bf4_2
    - packaging 23.0 pyhd8ed1ab_0
    - pathspec 0.11.0 pyhd8ed1ab_0
    - pip 22.3.1 pyhd8ed1ab_0
    - pluggy 1.0.0 pyhd8ed1ab_5
    - python 3.11.0 he550d4f_1_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 66.1.1 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.12.0 pyhd8ed1ab_0
  run:
    - python >=3.7
test:
  commands:
    - pip check
    - pytest -vv --pyargs traitlets --cov traitlets --no-cov-on-fail --cov-report
      term-missing:skip-covered --cov-fail-under=92
  imports:
    - traitlets
    - traitlets.config
  requires:
    - argcomplete>=2.0
    - pip
    - pytest-cov
    - pytest-mock
about:
  dev_url: https://github.com/ipython/traitlets
  doc_url: https://traitlets.readthedocs.org
  home: https://traitlets.readthedocs.org
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: Configuration system for Python applications
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Carreau
    - SylvainCorlay
    - blink1073
    - bollwyvl
    - davidbrochart
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
    - rmorshea
    - takluyver
    - zsailer
