CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '11.0'
build_platform: osx-64
c_compiler: '*'
channel_sources: conda-forge/label/rust_dev,conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: '*'
extend_keys:
- pin_run_as_build
- ignore_version
- ignore_build_only_deps
- extend_keys
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
macos_machine: arm64-apple-darwin20.0.0
numpy: '1.16'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '2.7'
python_abi_tag: cp39
python_impl: '*'
python_impl_version: '3.9'
python_implementation: cpython
python_version: '3.9'
r_base: '3.5'
target_platform: osx-arm64
vc: '*'
zip_keys:
- - python
  - python_impl
- - python_abi_tag
  - python_version
  - python_impl_version
  - python_implementation
