# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_f1vw_br1qm/clone/recipe, last modified Tue Jan 24 09:37:07 2023
# ------------------------------------------------

package:
  name: conda
  version: 23.1.0
source:
  sha256: ba417f2e77806be36ab99a7640262b263a2dc809398d9403ea5f6f8f14dcc1a8
  url: https://github.com/conda/conda/archive/23.1.0.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  string: py39hca03da5_0
requirements:
  build: []
  host:
    - ca-certificates 2023.01.10 hca03da5_0
    - certifi 2022.12.7 py39hca03da5_0
    - cffi 1.15.1 py39h80987f9_3
    - conda-package-handling 2.0.2 py39hca03da5_0
    - conda-package-streaming 0.7.0 py39hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.2 hca03da5_6
    - ncurses 6.3 h1a28f6b_3
    - openssl 1.1.1s h1a28f6b_0
    - pip 22.3.1 py39hca03da5_0
    - pluggy 1.0.0 py39hca03da5_1
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.9.16 hc0d8a6c_0
    - readline 8.2 h1a28f6b_0
    - ruamel.yaml 0.17.21 py39h1a28f6b_0
    - ruamel.yaml.clib 0.2.6 py39h1a28f6b_1
    - setuptools 65.6.3 py39hca03da5_0
    - sqlite 3.40.1 h7a7dc30_0
    - tk 8.6.12 hb8d0fd4_0
    - toolz 0.12.0 py39hca03da5_0
    - tqdm 4.64.1 py39hca03da5_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.10 h80987f9_1
    - zlib 1.2.13 h5a0b063_0
    - zstandard 0.18.0 py39h1a28f6b_0
  run:
    - conda-package-handling >=1.3.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - pyopenssl >=16.2.0
    - python >=3.9,<3.10.0a0
    - requests >=2.20.1,<3
    - ruamel.yaml >=0.11.14,<0.18
    - setuptools >=31.0.1
    - toolz >=0.8.1
    - tqdm >=4
  run_constrained:
    - conda-build >=3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
    - conda-libmamba-solver >=22.12.0
    - cytoolz >=0.8.1
test:
  downstreams:
    - conda-smithy
  imports:
    - conda
    - conda_env
  requires: null
about:
  description: 'Conda is an open source package management system and environment
    management system for installing multiple versions of software packages and their
    dependencies and switching easily between them. It works on Linux, OS X and Windows,
    and was created for Python programs but can package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://docs.conda.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: f1d0257e-9505-4a2e-8cac-75cb11541b80
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - jezdez
    - jjhelmus
    - kalefranz
    - kenodegard
    - mbargull
    - mcg1969
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
    - travishathaway
  remote_url: git@github.com:AnacondaRecipes/conda-feedstock.git
  sha: 7fab1c6e974154e8da1e519bcbe58e94886e7ae9
