# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/clone-6vr93g8h/recipe, last modified Tue Jan 11 10:51:44 2022
# ------------------------------------------------

package:
  name: c-ares
  version: 1.18.1
source:
  sha256: 1a7d52a8a84a9fbffb1be9133c0f6e17217d91ea5a6fa61f6b4729cda78ebbcf
  url: https://c-ares.org/download/c-ares-1.18.1.tar.gz
build:
  number: '0'
  run_exports:
    - c-ares >=1.18.1,<2.0a0
  string: h1a28f6b_0
requirements:
  build:
    - ca-certificates 2021.10.26 hca03da5_2
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - cmake-no-system 3.16.5 hc377ac9_2
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - expat 2.4.1 hc377ac9_2
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.4.2 hc377ac9_2
    - libiconv 1.16 h1230e6a_0
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - ncurses 6.3 h1a28f6b_2
    - ninja 1.10.2 py39h525c30c_3
    - openssl 1.1.1j h1230e6a_0
    - python 3.9.7 hc70090a_1
    - readline 8.1.2 h1a28f6b_0
    - sqlite 3.37.0 h1058600_0
    - tapi 1100.0.11 ha21211d_0
    - tk 8.6.11 hb8d0fd4_0
    - tzdata 2021e hda174b7_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 h5a0b063_4
  run: []
  run_constraint:
    - c-ares-static <0a0
about:
  dev_url: https://github.com/c-ares/c-ares
  doc_url: https://c-ares.org/docs.html
  home: https://c-ares.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
