# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jul 19 05:11:55 2022
# ------------------------------------------------

package:
  name: soupsieve
  version: 2.3.2.post1
source:
  sha256: fc53893b3da2c33de295667a0e19f078c14bf86544af307354de5fcf12a3f30d
  url: https://pypi.io/packages/source/s/soupsieve/soupsieve-2.3.2.post1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/soupsieve_1658207591808/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.6.15 ha878542_0
    - editables 0.3 pyhd8ed1ab_0
    - hatchling 1.5.0 pyhd8ed1ab_0
    - importlib-metadata 4.11.4 py310hff52083_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.1.0 h8d9b700_16
    - libgomp 12.1.0 h8d9b700_16
    - libnsl 2.0.0 h7f98852_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.12 h166bdaf_2
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.5 h166bdaf_0
    - packaging 21.3 pyhd8ed1ab_0
    - pathspec 0.9.0 pyhd8ed1ab_0
    - pip 22.1.2 pyhd8ed1ab_0
    - pluggy 1.0.0 py310hff52083_3
    - pyparsing 3.0.9 pyhd8ed1ab_0
    - python 3.10.5 ha86cf86_0_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1.2 h0f457ee_0
    - setuptools 63.2.0 py310hff52083_0
    - sqlite 3.39.1 h4ff8645_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2022a h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h516909a_1
    - zipp 3.8.0 pyhd8ed1ab_0
    - zlib 1.2.12 h166bdaf_2
  run:
    - python >=3.6
test:
  imports:
    - soupsieve
  requires:
    - beautifulsoup4
about:
  home: http://facelessuser.github.io/soupsieve
  license: MIT
  license_file: LICENSE.md
  summary: A modern CSS selector implementation for BeautifulSoup
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jschueller
