# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Feb  9 22:43:00 2023
# ------------------------------------------------

package:
  name: zipp
  version: 3.13.0
source:
  sha256: 23f70e964bc11a34cef175bc90ba2914e1e4545ea1e3e2f67c079671883f9cb6
  url: https://pypi.io/packages/source/z/zipp/zipp-3.13.0.tar.gz
build:
  noarch: python
  number: '0'
  script: '/home/conda/feedstock_root/build_artifacts/zipp_1675982654259/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps --ignore-installed -vv '
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.8 h0b41bf4_0
    - packaging 23.0 pyhd8ed1ab_0
    - pip 23.0 pyhd8ed1ab_0
    - python 3.11.0 he550d4f_1_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 67.1.0 pyhd8ed1ab_0
    - setuptools-scm 6.4.2 pyhd8ed1ab_0
    - setuptools_scm 6.4.2 hd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - toml 0.10.2 pyhd8ed1ab_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  commands:
    - python -m unittest tests/test_zipp.py
    - pip check
  imports:
    - zipp
  requires:
    - func_timeout
    - importlib_metadata
    - jaraco.functools
    - jaraco.itertools
    - more-itertools
    - pip
  source_files:
    - tests
about:
  dev_url: https://github.com/jaraco/zipp
  doc_url: https://zipp.readthedocs.io/en/latest
  home: https://github.com/jaraco/zipp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pathlib-compatible Zipfile object wrapper
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - nehaljwani
