# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/tmpcc0032zu/recipe, last modified Thu Nov  4 08:59:15 2021
# ------------------------------------------------

package:
  name: libedit
  version: 3.1.20210910
source:
  fn: libedit-20210910-3.1.tar.gz
  patches:
    - 0001-prefer-tinfo-over-curses-and-termcap.patch
  sha256: 6792a6a992050762edcca28ff3318cdb7de37dccf7bc30db59fcd7017eed13c5
  url: http://thrysoee.dk/editline/libedit-20210910-3.1.tar.gz
build:
  number: '0'
  run_exports:
    - libedit >=3.1.20210910,<3.2.0a0
  string: h1a28f6b_0
requirements:
  build:
    - autoconf 2.69 pl5340h1230e6a_1
    - automake 1.16.2 pl5340hca03da5_1
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - patch 2.7.6 h1a28f6b_1001
    - perl 5.34.0 h1230e6a_0
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  host:
    - ncurses 6.3 h1a28f6b_0
  run:
    - ncurses >=6.3,<7.0a0
test:
  commands:
    - test -f $PREFIX/lib/libedit.dylib
about:
  description: 'This is an autotool- and libtoolized port of the NetBSD Editline library

    (libedit). This Berkeley-style licensed command line editor library provides

    generic line editing, history, and tokenization functions, similar to those

    found in GNU Readline

    '
  home: http://thrysoee.dk/editline/
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: Editline Library (libedit)
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - djsutherland
    - mingwandroid
    - scopatz
