# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/pyrsistent-feedstock/recipe, last modified Sat Aug  7 09:30:02 2021
# ------------------------------------------------

package:
  name: pyrsistent
  version: 0.18.0
source:
  sha256: 773c781216f8c2900b42a7b638d5b517bb134ae1acbebe4d1e8f1f41ea60eb4b
  url: https://pypi.io/packages/source/p/pyrsistent/pyrsistent-0.18.0.tar.gz
build:
  number: '0'
  script: /Users/ktietz/demo/mc3/conda-bld/pyrsistent_1628941062930/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . -vv
  string: py39h1a28f6b_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h7dde238_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  host:
    - attrs 21.2.0 pyhd3eb1b0_0
    - ca-certificates 2021.4.13 hca03da5_1
    - certifi 2021.5.30 py39hca03da5_0
    - expat 2.4.1 hc377ac9_2
    - iniconfig 1.1.1 pyhd3eb1b0_0
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.3 hc4ed4cf_2
    - libiconv 1.16 h1230e6a_0
    - more-itertools 8.8.0 pyhd3eb1b0_0
    - ncurses 6.2 hc4ed4cf_0
    - openssl 1.1.1j h1230e6a_0
    - packaging 21.0 pyhd3eb1b0_0
    - pip 21.2.2 py39hca03da5_0
    - pluggy 0.13.1 py39hca03da5_0
    - py 1.10.0 pyhd3eb1b0_0
    - pyparsing 2.4.7 pyhd3eb1b0_0
    - pytest 6.2.3 py39hca03da5_2
    - pytest-runner 5.3.1 pyhd3eb1b0_0
    - python 3.9.6 hc70090a_4
    - readline 8.1 h1230e6a_0
    - setuptools 52.0.0 py39hca03da5_0
    - sqlite 3.35.4 h9835d80_0
    - tk 8.6.10 h6b60437_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2021a h5d7bf9c_0
    - wheel 0.37.0 pyhd3eb1b0_0
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 hca03da5_3
  run:
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
  imports:
    - pyrsistent
  requires:
    - pip
about:
  dev_url: http://github.com/tobgu/pyrsistent/
  doc_url: https://github.com/tobgu/pyrsistent/blob/master/README.rst
  home: http://github.com/tobgu/pyrsistent/
  license: MIT
  license_family: MIT
  license_file: LICENSE.mit
  summary: Persistent/Functional/Immutable data structures
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
