# This file created by conda-build 3.22.0
# ------------------------------------------------

package:
  name: jsonschema
  version: 4.17.3
source:
  sha256: 0f864437ab8b6076ba6707453ef8f98a6a0d512a80e93f8abdb676f737ecb60d
  url: https://pypi.io/packages/source/j/jsonschema/jsonschema-4.17.3.tar.gz
build:
  entry_points:
    - jsonschema = jsonschema.cli:main
  noarch: python
  number: 0
  script: /home/conda/feedstock_root/build_artifacts/jsonschema-meta_1669810440410/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.9.24 ha878542_0
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h166bdaf_0
    - packaging 21.3 pyhd8ed1ab_0
    - pip 22.3.1 pyhd8ed1ab_0
    - pyparsing 3.0.9 pyhd8ed1ab_0
    - python 3.11.0 ha86cf86_0_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 65.5.1 pyhd8ed1ab_0
    - setuptools-scm 7.0.5 pyhd8ed1ab_1
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.4.0 hd8ed1ab_0
    - typing_extensions 4.4.0 pyha770c72_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - attrs >=17.4.0
    - importlib-metadata
    - importlib_resources >=1.4.0
    - pkgutil-resolve-name >=1.3.10
    - pyrsistent !=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
    - python >=3.7
    - typing_extensions
test:
  commands:
    - pip check
    - jsonschema --version
    - jsonschema --help
    - jsonschema --version | grep 4\.17\.3
  imports:
    - jsonschema
  requires:
    - pip
about:
  dev_url: https://github.com/python-jsonschema/jsonschema
  doc_source_url: https://github.com/python-jsonschema/jsonschema/blob/v4.17.3/docs/index.rst
  doc_url: https://python-jsonschema.readthedocs.org
  home: https://github.com/python-jsonschema/jsonschema
  license: MIT
  license_file: COPYING
  summary: An implementation of JSON Schema validation for Python
extra:
  copy_test_source_files: true
  feedstock-name: jsonschema
  final: true
  recipe-maintainers:
    - bollwyvl
    - minrk
    - nehaljwani
    - ocefpaf
