# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jan 24 04:41:20 2023
# ------------------------------------------------

package:
  name: bleach
  version: 6.0.0
source:
  sha256: 1a1a85c1595e07d8db14c5f09f09e6433502c51c595970edc090551f0db99414
  url: https://pypi.io/packages/source/b/bleach/bleach-6.0.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/bleach_1674535352125/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vvv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h0b41bf4_1
    - pip 22.3.1 pyhd8ed1ab_0
    - python 3.11.0 he550d4f_1_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 66.1.1 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - packaging
    - python >=3.6
    - setuptools
    - six >=1.9.0
    - webencodings
test:
  commands:
    - pip check
  imports:
    - bleach
  requires:
    - pip
about:
  description: 'Bleach is an allowed-list-based HTML sanitizing library that escapes
    or

    strips markup and attributes.

    '
  dev_url: https://github.com/mozilla/bleach
  doc_source_url: https://github.com/mozilla/bleach/blob/master/docs/index.rst
  doc_url: https://bleach.readthedocs.io/
  home: https://github.com/mozilla/bleach
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Easy, whitelist-based HTML-sanitizing tool
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - minrk
    - ocefpaf
