# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Sep 14 07:06:31 2021
# ------------------------------------------------

package:
  name: pandocfilters
  version: 1.5.0
source:
  sha256: 0b679503337d233b4339a817bfc8c50064e2eff681314376a47cb582305a7a38
  url: https://pypi.io/packages/source/p/pandocfilters/pandocfilters-1.5.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h9c3ff4c_1
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgomp 11.1.0 hc902ee8_8
    - libstdcxx-ng 11.1.0 h56837e0_8
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1l h7f98852_0
    - pip 21.2.4 pyhd8ed1ab_0
    - python 3.8.10 hb7a2778_2_cpython
    - python_abi 3.8 2_cp38
    - readline 8.1 h46c0cb4_0
    - setuptools 58.0.4 py38h578d9bd_0
    - sqlite 3.36.0 h9cd32fc_1
    - tk 8.6.11 h27826a3_1
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3
test:
  commands:
    - pip check
  imports:
    - pandocfilters
  requires:
    - pip
about:
  dev_url: https://github.com/jgm/pandocfilters
  home: https://github.com/jgm/pandocfilters
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A python module for writing pandoc filters
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ickc
    - minrk
