# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Oct 24 15:42:19 2022
# ------------------------------------------------

package:
  name: pandoc
  version: 2.19.2
source:
  sha256: 5cebed5bfa8daa8c3f7ba0c29b0c84b36fd279bdcd25891d3ae9843fa2c98592
  url: https://github.com/jgm/pandoc/archive/refs/tags/2.19.2.tar.gz
build:
  binary_relocation: false
  missing_dso_whitelist:
    - /usr/lib/libcharset.1.dylib
    - /usr/lib/libiconv.2.dylib
    - /usr/lib/libz.1.dylib
  number: '1'
  string: hce30654_1
requirements:
  build:
    - stack 2.9.1 h694c41f_0
  host: []
  run: []
test:
  commands:
    - type pandoc
    - pandoc --version
    - pandoc --help
about:
  description: 'Pandoc is a Haskell library for converting from one markup format
    to

    another, and a command-line tool that uses this library.

    '
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/blob/master/MANUAL.txt
  doc_url: http://pandoc.org/MANUAL.html
  home: http://pandoc.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYRIGHT
  summary: The universal markup converter
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jankatins
    - kiwi0fruit
    - ocefpaf
