# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Oct 31 16:09:55 2022
# ------------------------------------------------

package:
  name: pluggy
  version: 1.0.0
source:
  sha256: 4224373bacce55f955a878bf9cfa763c1e360858e330072059e10bad68531159
  url: https://pypi.io/packages/source/p/pluggy/pluggy-1.0.0.tar.gz
build:
  noarch: python
  number: '5'
  script: /home/conda/feedstock_root/build_artifacts/pluggy_1667232663820/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_5
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.9.24 ha878542_0
    - ld_impl_linux-64 2.39 hc81fddc_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.39.4 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.5 h166bdaf_2
    - packaging 21.3 pyhd8ed1ab_0
    - pip 22.3 pyhd8ed1ab_0
    - pyparsing 3.0.9 pyhd8ed1ab_0
    - python 3.11.0 ha86cf86_0_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 65.5.0 pyhd8ed1ab_0
    - setuptools-scm 7.0.5 pyhd8ed1ab_1
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.4.0 hd8ed1ab_0
    - typing_extensions 4.4.0 pyha770c72_0
    - tzdata 2022e h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.8
test:
  commands:
    - pip check
  imports:
    - pluggy
  requires:
    - pip
about:
  dev_url: https://github.com/pytest-dev/pluggy/
  doc_url: https://pluggy.readthedocs.io/en/latest/
  home: https://github.com/pytest-dev/pluggy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Plugin registration and hook calling for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - adriendelsalle
    - johnnygenomics
    - nicoddemus
