# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: nbconvert-core
  version: 7.2.9
source:
  sha256: a42c3ac137c64f70cbe4d763111bf358641ea53b37a01a5c202ed86374af5234
  url: https://pypi.io/packages/source/n/nbconvert/nbconvert-7.2.9.tar.gz
build:
  entry_points:
    - jupyter-dejavu = nbconvert.nbconvertapp:dejavu_main
    - jupyter-nbconvert = nbconvert.nbconvertapp:main
  noarch: python
  number: 0
  script: /home/conda/feedstock_root/build_artifacts/nbconvert-meta_1674590374792/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv --no-deps
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h0b41bf4_1
    - pip 22.3.1 pyhd8ed1ab_0
    - python 3.11.0 he550d4f_1_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 66.1.1 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - beautifulsoup4
    - bleach
    - defusedxml
    - entrypoints >=0.2.2
    - jinja2 >=3.0
    - jupyter_core >=4.7
    - jupyterlab_pygments
    - markupsafe >=2.0
    - mistune >=2.0.3,<3
    - nbclient >=0.5.0
    - nbformat >=5.1
    - packaging
    - pandocfilters >=1.4.1
    - pygments >=2.4.1
    - python >=3.7
    - tinycss2
    - traitlets >=5.0
  run_constrained:
    - nbconvert =7.2.9=*_0
    - pandoc >=1.12.1
    - pyppeteer >=1,<1.1
test:
  commands:
    - jupyter nbconvert --version
    - jupyter dejavu --version
    - jupyter nbconvert --help
    - jupyter dejavu --help
  imports:
    - nbconvert
    - nbconvert.exporters
    - nbconvert.filters
    - nbconvert.postprocessors
    - nbconvert.preprocessors
    - nbconvert.resources
    - nbconvert.utils
    - nbconvert.writers
about:
  description: 'The nbconvert tool, jupyter nbconvert, converts notebooks to various
    other

    formats via Jinja templates. The nbconvert tool allows you to convert an

    .ipynb notebook file into various static formats.

    '
  dev_url: https://github.com/jupyter/nbconvert
  doc_url: https://nbconvert.readthedocs.org/
  home: https://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Converting Jupyter Notebooks
extra:
  copy_test_source_files: true
  feedstock-name: nbconvert
  final: true
  recipe-maintainers:
    - blink1073
    - bollwyvl
    - jakirkham
    - jasongrout
    - martinRenou
    - minrk
    - mpacer
    - mseal
    - ocefpaf
    - pelson
    - takluyver
