# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Sep  1 16:53:20 2022
# ------------------------------------------------

package:
  name: sniffio
  version: 1.3.0
source:
  sha256: e60305c5e5d314f5389259b7f22aaa33d8f7dee49763119234af3755c55b9101
  url: https://pypi.io/packages/source/s/sniffio/sniffio-1.3.0.tar.gz
build:
  noarch: python
  number: '0'
  script: '/home/conda/feedstock_root/build_artifacts/sniffio_1662051266223/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.6.15 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.1.0 h8d9b700_16
    - libgomp 12.1.0 h8d9b700_16
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.39.2 h753d276_1
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.12 h166bdaf_2
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.5 h166bdaf_1
    - pip 22.2.2 pyhd8ed1ab_0
    - python 3.10.6 ha86cf86_0_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 65.3.0 pyhd8ed1ab_1
    - tk 8.6.12 h27826a3_0
    - tzdata 2022c h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
test:
  imports:
    - sniffio
about:
  doc_url: https://sniffio.readthedocs.io
  home: https://github.com/python-trio/sniffio
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.APACHE2
  summary: Sniff out which async library your code is running under
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - nicoddemus
