# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Nov 30 07:56:21 2022
# ------------------------------------------------

package:
  name: nbclient
  version: 0.7.2
source:
  sha256: 884a3f4a8c4fc24bb9302f263e0af47d97f0d01fe11ba714171b320c8ac09547
  url: https://pypi.io/packages/source/n/nbclient/nbclient-0.7.2.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/nbclient_1669795076334/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.9.24 ha878542_0
    - editables 0.3 pyhd8ed1ab_0
    - hatchling 1.11.1 pyhd8ed1ab_0
    - importlib-metadata 5.1.0 pyha770c72_0
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h166bdaf_0
    - packaging 21.3 pyhd8ed1ab_0
    - pathspec 0.10.2 pyhd8ed1ab_0
    - pip 22.3.1 pyhd8ed1ab_0
    - pluggy 1.0.0 pyhd8ed1ab_5
    - pyparsing 3.0.9 pyhd8ed1ab_0
    - python 3.11.0 ha86cf86_0_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 65.5.1 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.11.0 pyhd8ed1ab_0
  run:
    - jupyter_client >=6.1.12
    - jupyter_core >=4.12,!=5.0.*
    - nbformat >=5.1
    - python >=3.7
    - traitlets >=5.3
test:
  imports:
    - nbclient
about:
  description: 'NBClient is a tool for parameterizing and executing Jupyter Notebooks.

    NBClient lets you execute notebooks. Similar in nature to jupyter_client, as the
    jupyter_client

    is to the jupyter protocol nbclient is to notebooks allowing for execution contexts
    to be run.

    '
  dev_url: https://github.com/jupyter/nbclient
  doc_source_url: https://github.com/jupyter/nbclient/tree/master/docs
  doc_url: https://nbclient.readthedocs.io
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client library for executing notebooks. Formally nbconvert's ExecutePreprocessor.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - davidbrochart
