# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Feb  2 20:28:49 2023
# ------------------------------------------------

package:
  name: nbclassic
  version: 0.5.1
source:
  sha256: 8e8ffce7582bb7a4baf11fa86a3d88b184e8e7df78eed4ead69f15aa4fc0e323
  url: https://pypi.io/packages/source/n/nbclassic/nbclassic-0.5.1.tar.gz
build:
  entry_points:
    - jupyter-nbclassic = nbclassic.notebookapp:main
    - jupyter-nbclassic-bundlerextension = nbclassic.bundler.bundlerextensions:main
    - jupyter-nbclassic-extension = nbclassic.nbextensions:main
    - jupyter-nbclassic-serverextension = nbclassic.serverextensions:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/nbclassic_1675369808718/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - anyio 3.6.2 pyhd8ed1ab_0
    - argon2-cffi 21.3.0 pyhd8ed1ab_0
    - argon2-cffi-bindings 21.2.0 py311hd4cff14_3
    - attrs 22.2.0 pyh71513ae_0
    - babel 2.11.0 pyhd8ed1ab_0
    - beautifulsoup4 4.11.2 pyha770c72_0
    - bleach 6.0.0 pyhd8ed1ab_0
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - cffi 1.15.1 py311h409f033_3
    - defusedxml 0.7.1 pyhd8ed1ab_0
    - deprecation 2.1.0 pyh9f0ad1d_0
    - entrypoints 0.4 pyhd8ed1ab_0
    - flit-core 3.8.0 pyhd8ed1ab_0
    - idna 3.4 pyhd8ed1ab_0
    - importlib-metadata 6.0.0 pyha770c72_0
    - importlib_metadata 6.0.0 hd8ed1ab_0
    - importlib_resources 5.10.2 pyhd8ed1ab_0
    - jinja2 3.1.2 pyhd8ed1ab_1
    - jsonschema 4.17.3 pyhd8ed1ab_0
    - jupyter-packaging 0.12.3 pyha770c72_0
    - jupyter_client 8.0.2 pyhd8ed1ab_0
    - jupyter_core 5.2.0 py311h38be061_0
    - jupyter_events 0.6.3 pyhd8ed1ab_0
    - jupyter_server 2.2.0 pyhd8ed1ab_0
    - jupyter_server_terminals 0.4.4 pyhd8ed1ab_1
    - jupyterlab_pygments 0.2.2 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsodium 1.0.18 h36c2ea0_1
    - libsqlite 3.40.0 h753d276_0
    - libstdcxx-ng 12.2.0 h46fd767_19
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - markupsafe 2.1.2 py311h2582759_0
    - mistune 2.0.4 pyhd8ed1ab_0
    - nbclient 0.7.2 pyhd8ed1ab_0
    - nbconvert-core 7.2.9 pyhd8ed1ab_0
    - nbformat 5.7.3 pyhd8ed1ab_0
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h0b41bf4_2
    - packaging 23.0 pyhd8ed1ab_0
    - pandocfilters 1.5.0 pyhd8ed1ab_0
    - pip 23.0 pyhd8ed1ab_0
    - pkgutil-resolve-name 1.3.10 pyhd8ed1ab_0
    - platformdirs 2.6.2 pyhd8ed1ab_0
    - prometheus_client 0.16.0 pyhd8ed1ab_0
    - ptyprocess 0.7.0 pyhd3deb0d_0
    - pycparser 2.21 pyhd8ed1ab_0
    - pygments 2.14.0 pyhd8ed1ab_0
    - pyrsistent 0.19.3 py311h2582759_0
    - python 3.11.0 he550d4f_1_cpython
    - python-dateutil 2.8.2 pyhd8ed1ab_0
    - python-fastjsonschema 2.16.2 pyhd8ed1ab_0
    - python-json-logger 2.0.4 pyhd8ed1ab_0
    - python_abi 3.11 3_cp311
    - pytz 2022.7.1 pyhd8ed1ab_0
    - pyyaml 6.0 py311hd4cff14_5
    - pyzmq 25.0.0 py311hd6ccaeb_0
    - readline 8.1.2 h0f457ee_0
    - rfc3339-validator 0.1.4 pyhd8ed1ab_0
    - rfc3986-validator 0.1.1 pyh9f0ad1d_0
    - send2trash 1.8.0 pyhd8ed1ab_0
    - setuptools 67.1.0 pyhd8ed1ab_0
    - six 1.16.0 pyh6c4a22f_0
    - sniffio 1.3.0 pyhd8ed1ab_0
    - soupsieve 2.3.2.post1 pyhd8ed1ab_0
    - terminado 0.17.1 pyh41d4057_0
    - tinycss2 1.2.1 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tomlkit 0.11.6 pyha770c72_0
    - tornado 6.2 py311hd4cff14_1
    - traitlets 5.9.0 pyhd8ed1ab_0
    - typing 3.10.0.0 pyhd8ed1ab_0
    - typing-extensions 4.4.0 hd8ed1ab_0
    - typing_extensions 4.4.0 pyha770c72_0
    - tzdata 2022g h191b570_0
    - webencodings 0.5.1 py_1
    - websocket-client 1.5.0 pyhd8ed1ab_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - yaml 0.2.5 h7f98852_2
    - zeromq 4.3.4 h9c3ff4c_1
    - zipp 3.12.0 pyhd8ed1ab_0
  run:
    - argon2-cffi
    - ipykernel
    - ipython_genutils
    - jinja2
    - jupyter_client >=6.1.1
    - jupyter_core >=4.6.1
    - jupyter_server >=1.17.0
    - nbconvert >=5
    - nbformat
    - nest-asyncio >=1.5
    - notebook-shim >=0.1.0
    - prometheus_client
    - python >=3.7
    - pyzmq >=17
    - send2trash >=1.8.0
    - terminado >=0.8.3
    - tornado >=6.1
    - traitlets >=4.2.1
test:
  commands:
    - pip check
    - jupyter nbclassic --help
    - jupyter nbclassic-extension --help
    - jupyter nbclassic-serverextension --help
    - jupyter nbclassic-bundlerextension --help
    - jupyter server extension list
    - jupyter server extension list 1>server_extensions 2>&1
    - cat server_extensions | grep -iE "nbclassic.*enabled"
    - cat server_extensions | grep -iE "nbclassic.*OK"
  downstreams:
    - jupyterlab
    - jupyterlab_server
  imports:
    - nbclassic
  requires:
    - pip
about:
  description: 'The Jupyter NbClassic is a web application that allows you to create
    and

    share documents that contain live code, equations, visualizations, and

    explanatory text. The NbClassic has support for multiple programming

    languages, sharing, and interactive widgets.

    '
  dev_url: https://github.com/jupyter/nbclassic
  doc_url: https://jupyter-notebook.readthedocs.io
  home: http://github.com/jupyterlab/nbclassic
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A web-based notebook environment for interactive computing
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - afshin
    - bollwyvl
    - jasongrout
    - jtpio
