# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/tmp4ygclk48/recipe, last modified Wed Nov 17 09:25:47 2021
# ------------------------------------------------

package:
  name: h5py
  version: 3.6.0
source:
  patches:
    - osx-arm64-hdf5.diff
    - osx-arm64.diff
  sha256: 840fca0787bca8ad2729b9c20e06a16f219e7a24ccc59fdf5177a05ec8472b2d
  url: https://github.com/h5py/h5py/archive/3.6.0.tar.gz
build:
  number: '0'
  script_env:
    - HDF5_HAS_ROS3=1
  string: py39h7fe8675_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_24
    - clang 12.0.0 hca03da5_4
    - clang-12 12.0.0 default_he099f3d_4
    - clang_osx-arm64 12.0.0 hcb56dc5_3
    - clangxx 12.0.0 default_he099f3d_4
    - compiler-rt 12.0.0 h4ccfd99_3
    - compiler-rt_osx-arm64 12.0.0 h4fb70ea_3
    - ld64_osx-arm64 530 h001ce53_24
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp12 12.0.0 default_he099f3d_4
    - libcxx 12.0.0 hf6beb65_1
    - libllvm12 12.0.0 h12f7ac0_4
    - llvm-tools 12.0.0 h12f7ac0_4
    - patch 2.7.6 h1a28f6b_1001
    - tapi 1100.0.11 ha21211d_0
    - zlib 1.2.11 hca03da5_3
  host:
    - blas 1.0 openblas
    - ca-certificates 2021.10.26 hca03da5_2
    - certifi 2021.5.30 py39hca03da5_1
    - cython 0.29.24 py39hc377ac9_0
    - expat 2.4.1 hc377ac9_2
    - hdf5 1.12.1 h5aa262f_1
    - krb5 1.19.2 h3b8d789_0
    - libcurl 7.71.1 h7623bd3_1
    - libcxx 12.0.0 hf6beb65_1
    - libedit 3.1.20210910 h1a28f6b_0
    - libffi 3.4.2 hc377ac9_2
    - libgfortran 5.0.0 11_1_0_h6a59814_26
    - libgfortran5 11.1.0 h6a59814_26
    - libiconv 1.16 h1230e6a_0
    - libopenblas 0.3.17 hcab743c_1
    - libssh2 1.9.0 hf27765b_1
    - llvm-openmp 12.0.0 haf9daa7_1
    - ncurses 6.3 h1a28f6b_2
    - numpy 1.19.5 py39habd9f23_3
    - openssl 1.1.1j h1230e6a_0
    - pip 21.2.4 py39hca03da5_0
    - pkg-config 0.29.2 h1a28f6b_0
    - pkgconfig 1.5.4 py39hca03da5_0
    - python 3.9.7 hc70090a_1
    - readline 8.1 h1a28f6b_0
    - setuptools 52.0.0 py39hca03da5_1
    - sqlite 3.36.0 h1058600_0
    - tk 8.6.11 hb8d0fd4_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 hca03da5_3
  run:
    - hdf5 >=1.12.1,<1.12.2.0a0
    - numpy >=1.19.5,<2.0a0
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
  imports:
    - h5py
    - h5py._hl
    - h5py.tests
    - h5py.tests.data_files
    - h5py.tests.test_vds
  requires:
    - curl
    - pip
    - pytest
    - pytest-mpi
about:
  dev_url: https://github.com/h5py/h5py
  home: http://www.h5py.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - minrk
    - ocefpaf
    - scopatz
    - tacaswell
