# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Apr 12 12:29:35 2021
# ------------------------------------------------

package:
  name: backports.functools_lru_cache
  version: 1.6.4
source:
  sha256: d5ed2169378b67d3c545e5600d363a923b09c456dab1593914935a68ad478271
  url: https://pypi.io/packages/source/b/backports.functools_lru_cache/backports.functools_lru_cache-1.6.4.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - backports 1.0 py_2
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py39hf3d152e_1
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.0.1 pyhd8ed1ab_0
    - python 3.9.2 hffdb5ce_0_cpython
    - python_abi 3.9 1_cp39
    - readline 8.0 he28a2e2_2
    - setuptools 49.6.0 py39hf3d152e_3
    - setuptools-scm 6.0.1 pyh44b312d_0
    - setuptools_scm 6.0.1 hd8ed1ab_0
    - sqlite 3.35.4 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - toml 0.10.2 pyhd8ed1ab_0
    - tzdata 2021a he74cb21_0
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - backports
    - python >=3.6
    - setuptools
test:
  imports:
    - backports.functools_lru_cache
about:
  dev_url: https://github.com/jaraco/backports.functools_lru_cache
  doc_url: https://pypi.python.org/pypi/backports.functools_lru_cache
  home: https://github.com/jaraco/backports.functools_lru_cache
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Backport of functools.lru_cache from Python 3.3 as published at ActiveState.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mariusvniekerk
    - stuertz
